# Generated by Django 5.2.7 on 2025-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube veya Vimeo'dan 'Embed' (Gömme) linkini buraya yapıştırın.",
                max_length=500,
                null=True,
                verbose_name="Video Gömme (Embed) URL'si",
            ),
        ),
    ]
