# Generated by Django 5.2.7 on 2025-11-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Proje listeleme sayfasında (kartta) görünecek ana resim.",
                null=True,
                upload_to="project_covers/",
                verbose_name="Kapak Resmi (Listeleme için)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(
                help_text="Örn: Streamlit, Plotly, Scikit-learn",
                max_length=200,
                verbose_name="Teknolojiler",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Proje Başlığı"),
        ),
        migrations.CreateModel(
            name="ProjectGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_gallery/")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resim Alt Yazısı",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
