version: "3.9"

services:
  web:
    container_name: django-portfolio
    build: .
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      echo 'from django.contrib.auth import get_user_model;
      User = get_user_model();
      User.objects.filter(username=\"admin\").exists() or
      User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin123\")' | python manage.py shell &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
