# Generated by Django 5.2.7 on 2025-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Gönderen İsim"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Gönderen E-posta"),
                ),
                ("message", models.TextField(verbose_name="Mesaj İçeriği")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Alınma Tarihi"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, verbose_name="Okundu olarak işaretle"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
