# Generated by Django 5.2.7 on 2025-11-02 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="İçerik"),
        ),
    ]
