"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import environ

# .env dosyasını okumak için 'kıdemli' (senior) kurulum
env = environ.Env()

# Projenin ana dizinindeki (BASE_DIR) '.env' dosyasını oku
environ.Env.read_env(env_file=BASE_DIR / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "pages.apps.PagesConfig",
    'projects.apps.ProjectsConfig',
    'blog.apps.BlogConfig',
    'contact.apps.ContactConfig',
    'ckeditor',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Yüklenen dosyaların (örn: proje resimleri) URL'si
MEDIA_URL = '/media/'

# Yüklenen dosyaların sunucuda (bilgisayarınızda)
# fiziksel olarak saklanacağı klasörün yolu
MEDIA_ROOT = BASE_DIR / 'media'

# tüm giden e-postaları 'runserver' terminaline yazdır.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# E-postaların kime gideceği (varsayılan)
ADMIN_EMAIL = 'emreaskinoffical@gmail.com'


# --- GÜVENLİK (SPAM KORUMASI) AYARLARI (Aşama 23 v1.1) ---
# Hız Sınırlaması (Ratelimit) için 'cache' (önbellek) ayarı
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "django-ratelimit-cache",
    }
}

# Sizin "binlerce mail atamasınlar" talebinizin çözümü:
RATELIMIT_RATE = '5/m' # Bir IP, dakikada (minute) 5'ten fazla istek atamasın
RATELIMIT_BLOCK = True # 5'i geçerse, isteği engelle (Hata döndür)

# --- CKEDITOR AYARLARI (Aşama 28 - v2.0) ---
# (P1: Blog'a resim/grafik yükleme talebiniz için)
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_ALLOW_NONIMAGE_FILES = False # Sadece resim yüklenebilsin (güvenlik)

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 400,
        'width': '100%',
        'toolbar_Custom': [
            # ... (mevcut toolbar ayarlarınız) ...
            ['Image', 'Table'],
            ['CodeSnippet'], 
        ],
        'extraPlugins': 'codesnippet',

        # --- YENİ EKLENEN SATIRLAR (Aşama 29) ---
        # (P1: Sizin 'lokalden alacam' talebiniz için)
        # CKEditor'e 'Upload' sekmesini göstermesi için 'filebrowser'ı kur
        'filebrowserImageUploadUrl': reverse_lazy('ckeditor_upload'),
        'filebrowserBrowseUrl': reverse_lazy('ckeditor_browse'),

        # 'image2' (gelişmiş resim) eklentisini kullan
        'extraPlugins': 'codesnippet,image2', 

        # 'image2' sürükle-bırak'ın 'Base64' (sizin 'textbox doldu' sorunu)
        # yerine 'upload' (sunucuya yükleme) yapmasını zorla
        'image2_uploadUrl': reverse_lazy('ckeditor_upload'),
        # --- BİTİŞ ---
    },
}